Dropdown: Remove parent onSelect, split Dropdown.Item to add Dropdown.NavItem
pinterest/gestalt pull request #1554
Opened 2021-06-11 17:50 UTC by dangerismycat

## Description

Dropdown (with children) currently presents a somewhat confusing API with multiple, overlapping event handlers. Similarly, Dropdown.Item doesn't provide guidance about how to use its various optional props, which can be put into two buckets: props for selection, and props for navigation. This PR accomplishes a few related things:
- Splits Dropdown.Item out to include Dropdown.NavItem. The former loses the props related to navigation (`href`, `isExternal`, `onClick`), while the latter loses the props related to selection (`onSelect`, `selected`). 
- Renames Dropdown.NavItem's selection handler from `handleSelect` to `onSelect` to match our event handler convention
- Removes the `onSelect` handler from Dropdown

### Links

- JIRA: https://jira.pinadmin.com/browse/PDS-2859

### Checklist

- [x] Updated Unit and Flow Tests
- [x] Updated documentation + accessibility tests
- [ ] Verified Accessibility: keyboard & screen reader interaction

2021-06-15 00:12 UTC, dangerismycat commented on docs/src/Dropdown.doc.js
> +        description={`If an item navigates to a new page, use Dropdown.Link with the required \`href\` prop. If the item navigates to a page outside of the current context, (either a non-Pinterest si
Expanded description

2021-06-15 00:12 UTC, dangerismycat commented on docs/src/Dropdown.doc.js
> -  const linkProps = {
Only used once, so inlined below to avoid spreading

2021-06-15 00:12 UTC, dangerismycat commented on packages/gestalt-codemods/next/dropdown-link.js
> +// yarn codemod --parser=flow -t=packages/gestalt-codemods/next/dropdown-link.js relative/path/to/your/code
Note to self: update `next` just before landing (along with the directory name)

2021-06-15 00:12 UTC, dangerismycat commented on packages/gestalt-codemods/next/dropdown-link.js
> +      // const nodePropertyName = node.openingElement.name.property?.name;
not really important for this codemod, but we pattern match off previous codemods, so a note to Future Us

2021-06-15 00:12 UTC, dangerismycat commented on packages/gestalt/src/Dropdown.css
> -
not sure why stylelint wasn't complaining about this…

2021-06-15 00:12 UTC, dangerismycat commented on packages/gestalt/src/Dropdown.js
> +function getChildrenOptions(childrenArray) {
Almost nothing changed here, except as noted. Pulled these helper functions out of the component for readability and to make their (lack of) dependencies clear

2021-06-15 00:12 UTC, dangerismycat commented on packages/gestalt/src/Dropdown.js
> +        ...(Array.isArray(currentItemChildren) ? currentItemChildren : [currentItemChildren]),
This is the change in this function. This fixes the "section with one item" bug

2021-06-15 00:12 UTC, dangerismycat commented on packages/gestalt/src/Dropdown.js
> +  return childrenArray.reduce((acc, child) => {
No real changes here aside from rewriting to use reduce instead of forEach

2021-06-15 00:12 UTC, dangerismycat commented on packages/gestalt/src/Dropdown.js
> -        onSelect?.({ event, item });
Removing Dropdown's onSelect

2021-06-15 00:12 UTC, dangerismycat commented on packages/gestalt/src/Dropdown.js
> +    } else if ([ESCAPE, TAB].includes(keyCode)) {
just a little DRY, no material changes

2021-06-15 00:12 UTC, dangerismycat commented on packages/gestalt/src/Dropdown.js
> +  // $FlowFixMe[incompatible-cast]
I tried to fix all these and was mostly shut down, but at least updated to more specific suppressions

2021-06-15 00:12 UTC, dangerismycat commented on packages/gestalt/src/Dropdown.jsdom.test.js
> +  it('should call link onClick when enter key is pressed', () => {
This is the test that's failing. I have no idea why. It doesn't register that mockOnClick was called.

2021-06-15 00:12 UTC, dangerismycat commented on packages/gestalt/src/DropdownItem.js
> +  // $FlowFixMe[signature-verification-failure] Beware, this thing is a mess to properly type
here there be 🐉

2021-06-15 00:12 UTC, dangerismycat commented on packages/gestalt/src/MenuOption.js
> +  onSelect?: ({|
updated this name, others are alphabetization

2021-06-15 00:12 UTC, dangerismycat commented on packages/gestalt/src/MenuOption.js
> +          // marginStart is for spacing relative to Badge, should not be moved to parent Flex's gap
a note to Future Me to not break things while refactoring 😂

2021-06-15 00:12 UTC, dangerismycat commented on packages/gestalt/src/MenuOption.js
> +          {/* TODO: this label needs to be translated */}
This probably works until we figure out a story for translation in Gestalt, but it's something we should address then

2021-06-15 00:12 UTC, dangerismycat commented on packages/gestalt/src/MenuOption.js
> +        color={index === hoveredItem ? 'lightGray' : 'transparent'}
not new, just inlined from above

2021-06-16 21:15 UTC, ayeshakmaz requested changes

2021-06-16 21:15 UTC, ayeshakmaz commented on packages/gestalt/src/Dropdown.js
> +    if (currentItemChildren && displayName === 'DropdownSection') {
It looks like the keyboard navigation is broken when Dropdown.Section only has one item (guessing the indexing gets off maybe?)

2021-06-17 00:00 UTC, ayeshakmaz approved these changes
LGTM 👍

2021-06-17 16:57 UTC, merged