Added Android Icon Page
pinterest/gestalt pull request #2333
Opened 2022-08-25 20:20 UTC by khalvy

Added the Android icon page along with playwright pages.

Thanks for creating a PR! Please follow this template and delete items/sections that are not relevant to your changes, including these instructions.

Please also make sure your [PR title](https://github.com/pinterest/gestalt/#releasing) matches our format: `{ComponentName}-{platform}: Description`

### Summary

#### What changed?

From a high level, what are the changes this PR introduces? (No need to recount line-by-line, we can see that.)

#### Why?

What is the purpose of this PR? Please include the context around these changes for Future Us. In addition to _what_ is changing, we need to know _why_ these changes are needed. Imagine someone is looking at these changes a year from now and needs to know why they were made.

### Links

- [Jira](https://jira.pinadmin.com/browse/GESTALT-XXXX)
- [TDD](link to Paper doc)
- [Figma](link to Figma file)

### Checklist

- [ ] Added unit and Flow Tests
- [ ] Added documentation + accessibility tests
- [ ] Verified accessibility: keyboard & screen reader interaction
- [ ] Checked dark mode, responsiveness, and right-to-left support
- [ ] Checked stakeholder feedback (e.g. Gestalt designers)

2022-08-25 21:45 UTC, rlingineni requested changes

2022-08-25 21:45 UTC, rlingineni commented on playwright/accessibility/Icon_Android.spec.mjs
> +  await page.goto('/android/icon');
@khalvy - looks like the accessibility check for the android icon/check failed.

If you click this button, you can see the error:
<img width="214" alt="image" src="https://user-images.githubusercontent.com/5509813/186774460-f17ddd1f-23dc-4ada-a0f5-d8084b49a168.png">

It seems like the images are missing alt-tags

2022-08-29 22:27 UTC, khalvy commented
Looks like this one went through too @rlingineni

2022-08-30 00:30 UTC, ayeshakmaz approved these changes

2022-08-30 00:30 UTC, merged