Docs: Add iOS & Android text field
pinterest/gestalt pull request #2334
Opened 2022-08-25 20:36 UTC by khalvy

Added the text field pages and updated the playwright documentation.

Thanks for creating a PR! Please follow this template and delete items/sections that are not relevant to your changes, including these instructions.

Please also make sure your [PR title](https://github.com/pinterest/gestalt/#releasing) matches our format: `{ComponentName}-{platform}: Description`

### Summary

#### What changed?

From a high level, what are the changes this PR introduces? (No need to recount line-by-line, we can see that.)

#### Why?

What is the purpose of this PR? Please include the context around these changes for Future Us. In addition to _what_ is changing, we need to know _why_ these changes are needed. Imagine someone is looking at these changes a year from now and needs to know why they were made.

### Links

- [Jira](https://jira.pinadmin.com/browse/GESTALT-XXXX)
- [TDD](link to Paper doc)
- [Figma](link to Figma file)

### Checklist

- [ ] Added unit and Flow Tests
- [ ] Added documentation + accessibility tests
- [ ] Verified accessibility: keyboard & screen reader interaction
- [ ] Checked dark mode, responsiveness, and right-to-left support
- [ ] Checked stakeholder feedback (e.g. Gestalt designers)

2022-08-25 21:50 UTC, rlingineni requested changes

2022-08-25 21:50 UTC, rlingineni commented on playwright/accessibility/TextField_Android.spec.mjs
> +import { test } from '@playwright/test';
Also, looks like there's some failed accessibility tests here. 

Related to missing alt-tags for the images

2022-08-29 21:28 UTC, khalvy commented
Checks have passed! @rlingineni is this good to go?

2022-08-29 23:15 UTC, rlingineni approved these changes

2022-08-29 23:54 UTC, ayeshakmaz approved these changes

2022-08-29 23:55 UTC, merged