Github Workflow: Auto-Format and Commit
pinterest/gestalt pull request #2705
Opened 2023-03-08 20:00 UTC by rlingineni

### Summary
Run `yarn format` and commit the results if there are auto-fixes. 

This enables us to do simple changes from the browser, and not worry about linting. 

Since we already have a build preview in place, this should be a good addition to faster changes from the web.

#### What changed and Why?

For a PR as tiny as this one https://github.com/pinterest/gestalt/pull/2702. It's frustrating to pull the branch code, and do the changes on my machine, run it locally and blah, because of a tiny formatting issue. It's likely an extra space. 

Likewise, to make changes to a [file](https://github.com/pinterest/gestalt/blob/master/docs/pages/get_started/faq.js) like this (e.g. add a new section). It should be fairly easy to do by copy-pasting, and adding an answer from the web console, but formatting becomes a pain. 

Soo hoping this step makes these kind of changes faster

2023-03-08 20:24 UTC, AlbertCarreras commented
@rlingineni run prettier, maybe for the last time?

2023-03-08 21:35 UTC, dangerismycat requested changes
I'm a bit hesitant to give write permissions to a third-party tool to solve something as minor as running prettier. Are we sure the need outweighs the potential security risk?

2023-03-08 21:35 UTC, dangerismycat commented on .github/workflows/main.yml
> +    branches: [main]
Our repo doesn't have a `main` — this will need to be `master`

2023-03-08 21:35 UTC, dangerismycat commented on .github/workflows/main.yml
> +          node-version: '14.x'
Node 14 is already a year past the end of active support and will soon cease security support: https://endoflife.date/nodejs

Let's use Node 18 here if possible, or at least 16

2023-03-08 21:35 UTC, dangerismycat commented on .github/workflows/main.yml
> +  format:
Without the `permissions` field I'm not sure that this is going to be able to do anything

2023-03-09 21:34 UTC, dangerismycat commented on .github/workflows/format.yml
> +            git config --global user.email "rlingineni@pinterest.com"
You can use the same account we use for releases, [pinterest-gestalt](https://github.com/pinterest-gestalt)

I would set the email as `pinterest-gestalt@gmail.com` and name as "Pinterest-Gestalt"

2023-03-14 16:13 UTC, rlingineni commented
@dangerismycat this is looking green now

2023-03-14 23:39 UTC, dangerismycat commented
I'm still seeing this step as waiting?
<img width="850" alt="Screen Shot 2023-03-14 at 4 39 16 PM" src="https://user-images.githubusercontent.com/12059539/225165887-f6c941d0-5b57-45ae-abf0-bb0a5cebc797.png">

2023-03-15 00:07 UTC, rlingineni commented
> I'm still seeing this step as waiting? <img alt="Screen Shot 2023-03-14 at 4 39 16 PM" width="850" src="https://user-images.githubusercontent.com/12059539/225165887-f6c941d0-5b57-45ae-abf0-bb0a5cebc797.png">

Yeah, it went green and then un-green after another change. I'll take a look tmmrw

2023-03-15 21:20 UTC, rlingineni commented
Abandoning this PR because it's running a previous version of a workflow file that doesn't exist, and that's causing things to fail (I think). Will remake it

2023-03-15 21:20 UTC, closed without merging