Eslint plugin: Update color names for Box inline style rule
pinterest/gestalt pull request #2987
Opened 2023-06-05 16:57 UTC by diyorbek

Thanks for creating a PR! Please follow this template and delete items/sections that are not relevant to your changes, including these instructions.

Please also make sure your [PR title](https://github.com/pinterest/gestalt/#releasing) matches our format: `{ComponentName}: Description (mentioning platform if relevant)`, or `{ComponentName}, {OtherComponentName}: Description (mentioning platform if relevant)` if multiple components are affected.

### Summary

#### What changed?

From a high level, what are the changes this PR introduces? (No need to recount line-by-line, we can see that.)

#### Why?

What is the purpose of this PR? Please include the context around these changes for Future Us. In addition to _what_ is changing, we need to know _why_ these changes are needed. Imagine someone is looking at these changes a year from now and needs to know why they were made.

### Links

- [Jira](https://jira.pinadmin.com/browse/GESTALT-XXXX)
- [TDD](link to Paper doc)
- [Figma](link to Figma file)

### Checklist

- [ ] Added unit and Flow Tests
- [ ] Added documentation + accessibility tests
- [ ] Verified accessibility: keyboard & screen reader interaction
- [ ] Checked dark mode, responsiveness, and right-to-left support
- [ ] Checked stakeholder feedback (e.g. Gestalt designers)

2023-06-06 22:54 UTC, AlbertCarreras commented
@diyorbek Can you add "Eslint plugin" to .github/pr-title-checker-config.json?

2023-06-06 22:55 UTC, AlbertCarreras approved these changes

2023-06-07 00:06 UTC, dangerismycat requested changes

2023-06-07 00:06 UTC, dangerismycat commented on packages/eslint-plugin-gestalt/package.json
> +    "eslint": "8.23.0"
Let's put this dependency change in a separate PR, and be sure to add the `dependencies` label to it

2023-06-07 10:31 UTC, diyorbek commented
@dangerismycat @AlbertCarreras Not sure why the PR title action is failing. I am assuming the action is using the old configuration.

2023-06-07 17:13 UTC, AlbertCarreras approved these changes

2023-06-07 17:14 UTC, merged